name       : lightdm-gtk-greeter
version    : 2.0.2
release    : 24
source     :
    - https://launchpad.net/lightdm-gtk-greeter/2.0/2.0.2/+download/lightdm-gtk-greeter-2.0.2.tar.gz : 8ee6d93d1d6837b3590f64ac4d5bac5db888a8861dff1cb2ef10f7816ad36690
license    : GPL-3.0
component  : desktop.lightdm
summary    : Customisable GTK+ Greeter for LightDM
description: |
    Customisable GTK+ Greeter for LightDM
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gmodule-export-2.0)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(x11)
    - pkgconfig(libxklavier)
    - gnome-common
setup      : |
    %patch -p1 < $pkgfiles/0001-Removed-exo-from-deps.patch
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    # Use a stateless default configuration
    install -D -m 00644 $pkgfiles/lightdm-gtk-greeter.conf $installdir/usr/share/lightdm/lightdm-gtk-greeter.conf.d/10_solus_default.conf
    rm -rf $installdir/etc
